from datetime import datetime

results = [{'id': '7ebe085081aa2928392e2b7ef0da361c',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Golden State Warriors', 'Utah Jazz'],
            'commence_time': 1615752600,
            'home_team': 'Golden State Warriors',
            'sites': [{'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.37, 2.95]}},
                      {'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.26, 3.8]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.31, 3.5]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758719,
                       'odds': {'h2h': [1.25, 3.65]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.29, 3.48]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.35, 3.25]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.29, 3.6]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.29, 3.6]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.29, 3.6]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.29, 3.6]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.37, 2.95]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.45, 2.5]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.46, 2.96], 'h2h_lay': [1.5, 3.2]}}],
            'sites_count': 13},
           {'id': '60a6ca37b1ab5fc3058eebb4097e199f',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Philadelphia 76ers', 'San Antonio Spurs'],
            'commence_time': 1615761600,
            'home_team': 'Philadelphia 76ers',
            'sites': [{'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.51, 2.66]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.53, 2.55]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.56, 2.48]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.56, 2.48]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.56, 2.48]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.56, 2.48]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.47, 2.6]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.51, 2.65]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.56, 2.6]}},
                      {'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.51, 2.7]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.51, 2.7]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.51, 2.65]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.5, 2.7]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.51, 2.65]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.51, 2.66]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.53, 2.65]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.53, 2.7]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.56, 2.74], 'h2h_lay': [1.57, 2.76]}}],
            'sites_count': 18},
           {'id': 'afa471f82fd511460ed4a90bdc9fd5db',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Miami Heat', 'Orlando Magic'],
            'commence_time': 1615763400,
            'home_team': 'Orlando Magic',
            'sites': [{'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.3, 3.65]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.29, 3.6]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.33, 3.45]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.33, 3.45]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.33, 3.45]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.33, 3.45]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.3, 3.4]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.32, 3.4]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.33, 3.5]}},
                      {'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.29, 3.8]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.28, 3.8]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.32, 3.45]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.33, 3.5]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.32, 3.5]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.33, 3.45]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.33, 3.5]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.3, 3.7]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.34, 3.8], 'h2h_lay': [1.36, 3.9]}}],
            'sites_count': 18},
           {'id': 'abbfc18d4df6523106533d96950f298a',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Atlanta Hawks', 'Cleveland Cavaliers'],
            'commence_time': 1615765200,
            'home_team': 'Atlanta Hawks',
            'sites': [{'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.44, 2.88]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.44, 2.8]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.48, 2.75]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.48, 2.75]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.48, 2.75]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.48, 2.75]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.44, 2.75]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.45, 2.75]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.45, 2.9]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.45, 2.9]}},
                      {'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.46, 2.9]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.44, 2.9]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.44, 2.85]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.43, 2.9]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.48, 2.76]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758506,
                       'odds': {'h2h': [1.44, 2.85]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.42, 3.0]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.49, 2.96], 'h2h_lay': [1.51, 3.05]}}],
            'sites_count': 18},
           {'id': '06463be85acf2f51ba14c04beea86c10',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Boston Celtics', 'Houston Rockets'],
            'commence_time': 1615767000,
            'home_team': 'Houston Rockets',
            'sites': [{'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.13, 5.75]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.15, 6.0]}},
                      {'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.15, 6.0]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.16, 5.6]}},
                      {'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.15, 5.8]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.17, 5.5]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.12, 6.0]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.14, 6.06]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.15, 5.6]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.17, 5.3]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.17, 5.3]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.17, 5.3]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.17, 5.3]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.17, 6.6], 'h2h_lay': [1.18, 7.0]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.14, 6.0]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.17, 5.25]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.15, 5.8]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.15, 5.7]}}],
            'sites_count': 18},
           {'id': 'a6a9ecb42c262a1d49113306cd2bb2c2',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Minnesota Timberwolves', 'Portland Trail Blazers'],
            'commence_time': 1615767000,
            'home_team': 'Minnesota Timberwolves',
            'sites': [{'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [2.76, 1.48]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [2.6, 1.47]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'caesars',
                       'site_nice': 'Caesars',
                       'last_update': 1615758787,
                       'odds': {'h2h': [2.75, 1.5]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [2.66, 1.51]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [2.7, 1.48]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [2.7, 1.48]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [2.7, 1.48]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [2.7, 1.48]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [2.75, 1.5]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [2.88, 1.52], 'h2h_lay': [2.94, 1.53]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [2.7, 1.5]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [2.8, 1.47]}},
                      {'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [2.8, 1.48]}}],
            'sites_count': 18},
           {'id': '1745edd8448d22602c8dbc97b5f608ee',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Los Angeles Clippers', 'New Orleans Pelicans'],
            'commence_time': 1615770600,
            'home_team': 'New Orleans Pelicans',
            'sites': [{'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.44, 2.95]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.44, 2.95]}},
                      {'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.38, 2.94]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.44, 2.8]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.45, 2.9]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.4, 2.9]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.46, 2.81]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.43, 2.95]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.44, 2.85]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.42, 2.95]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.42, 2.95]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.42, 2.95]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.42, 2.95]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.44, 2.8]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.43, 2.9]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.43, 2.9]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.47, 3.05], 'h2h_lay': [1.49, 3.1]}}],
            'sites_count': 17},
           {'id': 'd03b9b3e55fd583839182eae01ec98a3',
            'sport_key': 'basketball_nba',
            'sport_nice': 'NBA',
            'teams': ['Chicago Bulls', 'Toronto Raptors'],
            'commence_time': 1615770600,
            'home_team': 'Chicago Bulls',
            'sites': [{'site_key': 'lowvig',
                       'site_nice': 'LowVig.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'betonlineag',
                       'site_nice': 'BetOnline.ag',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.66, 2.29]}},
                      {'site_key': 'fanduel',
                       'site_nice': 'FanDuel',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.69, 2.22]}},
                      {'site_key': 'pointsbetus',
                       'site_nice': 'PointsBet (US)',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'williamhill_us',
                       'site_nice': 'William Hill (US)',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'foxbet',
                       'site_nice': 'FOX Bet',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.65, 2.2]}},
                      {'site_key': 'bookmaker',
                       'site_nice': 'Bookmaker',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'gtbets',
                       'site_nice': 'GTbets',
                       'last_update': 1615758785,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'bovada',
                       'site_nice': 'Bovada',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'unibet',
                       'site_nice': 'Unibet',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.7, 2.23]}},
                      {'site_key': 'betrivers',
                       'site_nice': 'BetRivers',
                       'last_update': 1615758786,
                       'odds': {'h2h': [1.7, 2.23]}},
                      {'site_key': 'sugarhouse',
                       'site_nice': 'SugarHouse',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.7, 2.23]}},
                      {'site_key': 'draftkings',
                       'site_nice': 'DraftKings',
                       'last_update': 1615758788,
                       'odds': {'h2h': [1.7, 2.23]}},
                      {'site_key': 'betmgm',
                       'site_nice': 'BetMGM',
                       'last_update': 1615758787,
                       'odds': {'h2h': [1.67, 2.25]}},
                      {'site_key': 'mybookieag',
                       'site_nice': 'MyBookie.ag',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'intertops',
                       'site_nice': 'Intertops',
                       'last_update': 1615758784,
                       'odds': {'h2h': [1.67, 2.3]}},
                      {'site_key': 'betfair',
                       'site_nice': 'Betfair',
                       'last_update': 1615758779,
                       'odds': {'h2h': [1.72, 2.36], 'h2h_lay': [1.73, 2.4]}}],
            'sites_count': 17}]
holder = []

for games in results:
    holder.append(games['sites'])

game_one = holder[0]

home_odds = []
away_odds = []
for game in holder:
    for site in game:
        hodds = {}
        aodds = {}
        hodds[site['site_key']] = site['odds']['h2h'][0]
        aodds[site['site_key']] = site['odds']['h2h'][1]
        sort_hodds = sorted(hodds.items(), key=lambda x: x[1], reverse=True)
        sort_aodds = sorted(aodds.items(), key=lambda x: x[1], reverse=True)
        home_odds.append(sort_hodds)
        away_odds.append(aodds)
